In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

1. Download and load the data (csv file contains ';' as delimiter)

In [12]:
def load_df(file):
    """Loads the Dataset"""
    df = pd.read_csv(file, delimiter=';')
    return df

In [14]:
path = 'divorce.csv'
df = load_df(path)

2. Add column at position 0 with all values=1 (pandas.DataFrame.insert function). This is for input to the bias

In [16]:
df.insert(0, 'b', 1)
df

,b,Atr1,Atr2,Atr3,Atr4,Atr5,Atr6,Atr7,Atr8,Atr9,...,Atr46,Atr47,Atr48,Atr49,Atr50,Atr51,Atr52,Atr53,Atr54,Class
0,1,2,2,4,1,0,0,0,0,0,...,2,1,3,3,3,2,3,2,1,1
1,1,4,4,4,4,4,0,0,4,4,...,2,2,3,4,4,4,4,2,2,1
2,1,2,2,2,2,1,3,2,1,1,...,3,2,3,1,1,1,2,2,2,1
3,1,3,2,3,2,3,3,3,3,3,...,2,2,3,3,3,3,2,2,2,1
4,1,2,2,1,1,1,1,0,0,0,...,2,1,2,3,2,2,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,1,0,0,0,0,0,0,0,0,0,...,1,0,4,1,1,4,2,2,2,0
166,1,0,0,0,0,0,0,0,0,0,...,4,1,2,2,2,2,3,2,2,0
167,1,1,1,0,0,0,0,0,0,0,...,3,0,2,0,1,1,3,0,0,0
168,1,0,0,0,0,0,0,0,0,0,...,3,3,2,2,3,2,4,3,1,0
169,1,0,0,0,0,0,0,0,1,0,...,3,4,4,0,1,3,3,3,1,0

3. Define X matrix (independent features) and y vector (target feature) as numpy arrays

In [32]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1:]

5. Split the dataset into 85% for training and rest 15% for testing (sklearn.model_selection.train_test_split function)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15)

6. Follow logistic regression class and fill code where highlighted:

7. Write sigmoid function to predict probabilities

In [42]:
# Randomly inititalised weights
w = 0.01 * np.random.randn(X.shape[1], 1)
b = 1

In [45]:
# Regression
def h_x(w, b, X, y):
    z = np.dot(w.T, X) + b
    return z

In [46]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

Vectorised Log Loss: ${1/m}{(-y^T)log(h) - (1-y)^T log(1-h)}$

In [27]:
def logistic_loss(w, b, X, y):
    m = len(y) # no of training examples
    # 1/m * np.matmul(-y.T, np.log(y_pred))